name: Deploy to GCP Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        version: 'latest'  # or specify a version like '419.0.0'

    - name: Authenticate with service account
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > gcloud-key.json
        gcloud auth activate-service-account --key-file=gcloud-key.json

    - name: Deploy to Cloud Storage Bucket
      run: |
        gsutil -m rsync -r ./ gs://geriprifti.com
